"""
VIGIL LABS - Preconfigured Tool Store Catalog
80+ cybersecurity, networking, OSINT, forensics, and DevOps tools.
"""

TOOL_CATALOG = [
    # === RECON / SCANNING ===
    {"name": "Nmap", "slug": "nmap", "category": "Recon / Scanning", "description": "Network discovery and security auditing tool", "executable_name": "nmap", "install_method": "apt", "install_command_linux": "sudo apt install -y nmap", "install_command_windows": "choco install nmap -y", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "github_url": "https://github.com/nmap/nmap", "is_featured": True, "tags": ["network", "scanner", "ports"]},
    {"name": "Masscan", "slug": "masscan", "category": "Recon / Scanning", "description": "Fastest Internet port scanner", "executable_name": "masscan", "install_method": "apt", "install_command_linux": "sudo apt install -y masscan", "risk_level": "high", "supports_linux": True, "supports_windows": True, "github_url": "https://github.com/robertdavidgraham/masscan", "tags": ["network", "fast-scanner"]},
    {"name": "Rustscan", "slug": "rustscan", "category": "Recon / Scanning", "description": "Fast port scanner written in Rust", "executable_name": "rustscan", "install_method": "github", "github_repo": "RustScan/RustScan", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "tags": ["rust", "fast-scanner"]},
    {"name": "Amass", "slug": "amass", "category": "Recon / Scanning", "description": "In-depth attack surface mapping and asset discovery", "executable_name": "amass", "install_method": "apt", "install_command_linux": "sudo apt install -y amass", "risk_level": "low", "supports_linux": True, "supports_windows": True, "github_url": "https://github.com/owasp-amass/amass", "tags": ["recon", "subdomain", "osint"]},
    {"name": "Subfinder", "slug": "subfinder", "category": "Recon / Scanning", "description": "Fast passive subdomain enumeration tool", "executable_name": "subfinder", "install_method": "github", "github_repo": "projectdiscovery/subfinder", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["subdomain", "passive"]},
    {"name": "Assetfinder", "slug": "assetfinder", "category": "Recon / Scanning", "description": "Find domains and subdomains related to a given domain", "executable_name": "assetfinder", "install_method": "github", "github_repo": "tomnomnom/assetfinder", "risk_level": "low", "supports_linux": True, "tags": ["subdomain", "recon"]},
    {"name": "WhatWeb", "slug": "whatweb", "category": "Recon / Scanning", "description": "Web scanner that identifies websites and technologies", "executable_name": "whatweb", "install_method": "apt", "install_command_linux": "sudo apt install -y whatweb", "risk_level": "low", "supports_linux": True, "tags": ["web", "fingerprint"]},
    {"name": "DNSx", "slug": "dnsx", "category": "Recon / Scanning", "description": "Fast and multi-purpose DNS toolkit", "executable_name": "dnsx", "install_method": "github", "github_repo": "projectdiscovery/dnsx", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["dns", "resolution"]},
    {"name": "Httpx", "slug": "httpx", "category": "Recon / Scanning", "description": "Fast HTTP probing tool", "executable_name": "httpx", "install_method": "github", "github_repo": "projectdiscovery/httpx", "risk_level": "low", "supports_linux": True, "supports_windows": True, "is_featured": True, "tags": ["http", "probe", "web"]},

    # === WEB TESTING ===
    {"name": "Nikto", "slug": "nikto", "category": "Web Testing", "description": "Web server scanner for vulnerabilities", "executable_name": "nikto", "install_method": "apt", "install_command_linux": "sudo apt install -y nikto", "risk_level": "medium", "supports_linux": True, "tags": ["web", "vulnerability", "scanner"]},
    {"name": "Nuclei", "slug": "nuclei", "category": "Web Testing", "description": "Fast vulnerability scanner based on templates", "executable_name": "nuclei", "install_method": "github", "github_repo": "projectdiscovery/nuclei", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "is_featured": True, "tags": ["vulnerability", "templates", "fast"]},
    {"name": "Dirsearch", "slug": "dirsearch", "category": "Web Testing", "description": "Web path scanner/directory brute-forcer", "executable_name": "dirsearch", "install_method": "pip", "install_command_linux": "pip3 install dirsearch", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["web", "directory", "bruteforce"]},
    {"name": "Gobuster", "slug": "gobuster", "category": "Web Testing", "description": "Directory/file & DNS busting tool written in Go", "executable_name": "gobuster", "install_method": "apt", "install_command_linux": "sudo apt install -y gobuster", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["web", "directory", "dns"]},
    {"name": "Feroxbuster", "slug": "feroxbuster", "category": "Web Testing", "description": "Fast, recursive content discovery tool", "executable_name": "feroxbuster", "install_method": "apt", "install_command_linux": "sudo apt install -y feroxbuster", "risk_level": "low", "supports_linux": True, "supports_windows": True, "github_url": "https://github.com/epi052/feroxbuster", "tags": ["web", "recursive", "fast"]},
    {"name": "ffuf", "slug": "ffuf", "category": "Web Testing", "description": "Fast web fuzzer written in Go", "executable_name": "ffuf", "install_method": "apt", "install_command_linux": "sudo apt install -y ffuf", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "is_featured": True, "tags": ["fuzzer", "web", "fast"]},
    {"name": "Dalfox", "slug": "dalfox", "category": "Web Testing", "description": "Parameter analysis and XSS scanning tool", "executable_name": "dalfox", "install_method": "github", "github_repo": "hahwul/dalfox", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "tags": ["xss", "web", "scanner"]},

    # === VULNERABILITY / EXPLOIT ===
    {"name": "SearchSploit", "slug": "searchsploit", "category": "Vulnerability / Exploit", "description": "Command-line search tool for Exploit-DB", "executable_name": "searchsploit", "install_method": "apt", "install_command_linux": "sudo apt install -y exploitdb", "risk_level": "low", "supports_linux": True, "tags": ["exploit", "search", "database"]},
    {"name": "Metasploit Framework", "slug": "metasploit", "category": "Vulnerability / Exploit", "description": "Advanced open-source exploitation framework", "executable_name": "msfconsole", "install_method": "apt", "install_command_linux": "sudo apt install -y metasploit-framework", "risk_level": "critical", "supports_linux": True, "supports_windows": True, "is_featured": True, "tags": ["exploit", "framework", "pentest"]},
    {"name": "CVEMap", "slug": "cvemap", "category": "Vulnerability / Exploit", "description": "Navigate the CVE jungle with ease", "executable_name": "cvemap", "install_method": "github", "github_repo": "projectdiscovery/cvemap", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["cve", "vulnerability"]},

    # === PAYLOAD / LAB UTILITIES ===
    {"name": "msfvenom", "slug": "msfvenom", "category": "Payload / Lab Utilities", "description": "Payload generation framework (part of Metasploit)", "executable_name": "msfvenom", "install_method": "apt", "install_command_linux": "sudo apt install -y metasploit-framework", "risk_level": "critical", "supports_linux": True, "tags": ["payload", "generation"]},
    {"name": "Veil", "slug": "veil", "category": "Payload / Lab Utilities", "description": "Generate payloads that bypass antivirus", "executable_name": "veil", "install_method": "github", "github_repo": "Veil-Framework/Veil", "risk_level": "critical", "supports_linux": True, "tags": ["evasion", "payload", "av-bypass"]},

    # === PASSWORD / HASH TESTING ===
    {"name": "Hashcat", "slug": "hashcat", "category": "Password / Hash Testing", "description": "World's fastest password recovery utility", "executable_name": "hashcat", "install_method": "apt", "install_command_linux": "sudo apt install -y hashcat", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "is_featured": True, "tags": ["password", "hash", "gpu"]},
    {"name": "John the Ripper", "slug": "john", "category": "Password / Hash Testing", "description": "Fast password cracker", "executable_name": "john", "install_method": "apt", "install_command_linux": "sudo apt install -y john", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "tags": ["password", "cracker"]},
    {"name": "Hydra", "slug": "hydra", "category": "Password / Hash Testing", "description": "Network login cracker supporting many protocols", "executable_name": "hydra", "install_method": "apt", "install_command_linux": "sudo apt install -y hydra", "risk_level": "high", "supports_linux": True, "supports_windows": True, "tags": ["bruteforce", "network", "login"]},
    {"name": "Medusa", "slug": "medusa", "category": "Password / Hash Testing", "description": "Speedy parallel network login auditor", "executable_name": "medusa", "install_method": "apt", "install_command_linux": "sudo apt install -y medusa", "risk_level": "high", "supports_linux": True, "tags": ["bruteforce", "parallel"]},
    {"name": "CeWL", "slug": "cewl", "category": "Password / Hash Testing", "description": "Custom wordlist generator by spidering websites", "executable_name": "cewl", "install_method": "apt", "install_command_linux": "sudo apt install -y cewl", "risk_level": "low", "supports_linux": True, "tags": ["wordlist", "generator"]},
    {"name": "Crunch", "slug": "crunch", "category": "Password / Hash Testing", "description": "Wordlist generator with specified character sets", "executable_name": "crunch", "install_method": "apt", "install_command_linux": "sudo apt install -y crunch", "risk_level": "low", "supports_linux": True, "tags": ["wordlist", "generator"]},

    # === WIRELESS / WIFI LAB ===
    {"name": "Aircrack-ng", "slug": "aircrack-ng", "category": "Wireless / WiFi Lab", "description": "Complete suite of WiFi security tools", "executable_name": "aircrack-ng", "install_method": "apt", "install_command_linux": "sudo apt install -y aircrack-ng", "risk_level": "high", "supports_linux": True, "tags": ["wifi", "cracking", "monitoring"]},
    {"name": "Kismet", "slug": "kismet", "category": "Wireless / WiFi Lab", "description": "Wireless network and device detector/sniffer", "executable_name": "kismet", "install_method": "apt", "install_command_linux": "sudo apt install -y kismet", "risk_level": "medium", "supports_linux": True, "tags": ["wifi", "sniffer", "detection"]},
    {"name": "Wifite", "slug": "wifite", "category": "Wireless / WiFi Lab", "description": "Automated wireless attack tool", "executable_name": "wifite", "install_method": "apt", "install_command_linux": "sudo apt install -y wifite", "risk_level": "high", "supports_linux": True, "tags": ["wifi", "automated"]},
    {"name": "Bettercap", "slug": "bettercap", "category": "Wireless / WiFi Lab", "description": "Swiss Army knife for network attacks and monitoring", "executable_name": "bettercap", "install_method": "apt", "install_command_linux": "sudo apt install -y bettercap", "risk_level": "high", "supports_linux": True, "tags": ["mitm", "network", "wifi"]},
    {"name": "Reaver", "slug": "reaver", "category": "Wireless / WiFi Lab", "description": "WPS brute force attack tool", "executable_name": "reaver", "install_method": "apt", "install_command_linux": "sudo apt install -y reaver", "risk_level": "high", "supports_linux": True, "tags": ["wps", "bruteforce"]},

    # === NETWORK ANALYSIS ===
    {"name": "Wireshark", "slug": "wireshark", "category": "Network Analysis", "description": "World's most popular network protocol analyzer", "executable_name": "wireshark", "install_method": "apt", "install_command_linux": "sudo apt install -y wireshark", "install_command_windows": "choco install wireshark -y", "risk_level": "low", "supports_linux": True, "supports_windows": True, "is_featured": True, "tags": ["packet", "capture", "analysis"]},
    {"name": "Tshark", "slug": "tshark", "category": "Network Analysis", "description": "Terminal-based network protocol analyzer", "executable_name": "tshark", "install_method": "apt", "install_command_linux": "sudo apt install -y tshark", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["packet", "cli"]},
    {"name": "Tcpdump", "slug": "tcpdump", "category": "Network Analysis", "description": "Command-line packet analyzer", "executable_name": "tcpdump", "install_method": "apt", "install_command_linux": "sudo apt install -y tcpdump", "risk_level": "low", "supports_linux": True, "tags": ["packet", "capture", "cli"]},
    {"name": "Ettercap", "slug": "ettercap", "category": "Network Analysis", "description": "Comprehensive suite for MITM attacks on LAN", "executable_name": "ettercap", "install_method": "apt", "install_command_linux": "sudo apt install -y ettercap-common", "risk_level": "high", "supports_linux": True, "tags": ["mitm", "arp", "sniffing"]},
    {"name": "Netdiscover", "slug": "netdiscover", "category": "Network Analysis", "description": "Active/passive ARP reconnaissance tool", "executable_name": "netdiscover", "install_method": "apt", "install_command_linux": "sudo apt install -y netdiscover", "risk_level": "low", "supports_linux": True, "tags": ["arp", "discovery"]},
    {"name": "Arp-scan", "slug": "arp-scan", "category": "Network Analysis", "description": "ARP scanning and fingerprinting tool", "executable_name": "arp-scan", "install_method": "apt", "install_command_linux": "sudo apt install -y arp-scan", "risk_level": "low", "supports_linux": True, "tags": ["arp", "scan"]},

    # === OSINT ===
    {"name": "theHarvester", "slug": "theharvester", "category": "OSINT", "description": "Gather emails, subdomains, hosts, employee names from public sources", "executable_name": "theHarvester", "install_method": "apt", "install_command_linux": "sudo apt install -y theharvester", "risk_level": "low", "supports_linux": True, "tags": ["email", "subdomain", "recon"]},
    {"name": "Sherlock", "slug": "sherlock", "category": "OSINT", "description": "Hunt down social media accounts by username", "executable_name": "sherlock", "install_method": "pip", "install_command_linux": "pip3 install sherlock-project", "risk_level": "low", "supports_linux": True, "supports_windows": True, "github_url": "https://github.com/sherlock-project/sherlock", "tags": ["social-media", "username"]},
    {"name": "SpiderFoot", "slug": "spiderfoot", "category": "OSINT", "description": "Open source intelligence automation tool", "executable_name": "spiderfoot", "install_method": "pip", "install_command_linux": "pip3 install spiderfoot", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["automation", "osint"]},
    {"name": "Recon-ng", "slug": "recon-ng", "category": "OSINT", "description": "Web reconnaissance framework", "executable_name": "recon-ng", "install_method": "apt", "install_command_linux": "sudo apt install -y recon-ng", "risk_level": "low", "supports_linux": True, "tags": ["framework", "recon"]},
    {"name": "Holehe", "slug": "holehe", "category": "OSINT", "description": "Check if email is used on different sites", "executable_name": "holehe", "install_method": "pip", "install_command_linux": "pip3 install holehe", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["email", "lookup"]},

    # === FORENSICS / MALWARE ANALYSIS ===
    {"name": "Volatility", "slug": "volatility", "category": "Forensics / Malware Analysis", "description": "Advanced memory forensics framework", "executable_name": "vol.py", "install_method": "pip", "install_command_linux": "pip3 install volatility3", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["memory", "forensics"]},
    {"name": "Binwalk", "slug": "binwalk", "category": "Forensics / Malware Analysis", "description": "Firmware analysis and extraction tool", "executable_name": "binwalk", "install_method": "apt", "install_command_linux": "sudo apt install -y binwalk", "risk_level": "low", "supports_linux": True, "tags": ["firmware", "extraction"]},
    {"name": "ExifTool", "slug": "exiftool", "category": "Forensics / Malware Analysis", "description": "Read, write, and manipulate file metadata", "executable_name": "exiftool", "install_method": "apt", "install_command_linux": "sudo apt install -y libimage-exiftool-perl", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["metadata", "images"]},
    {"name": "YARA", "slug": "yara", "category": "Forensics / Malware Analysis", "description": "Pattern matching tool for malware research", "executable_name": "yara", "install_method": "apt", "install_command_linux": "sudo apt install -y yara", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["malware", "patterns", "rules"]},
    {"name": "Radare2", "slug": "radare2", "category": "Forensics / Malware Analysis", "description": "Advanced commandline hexadecimal editor and disassembler", "executable_name": "r2", "install_method": "apt", "install_command_linux": "sudo apt install -y radare2", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["reverse", "disassembler", "binary"]},

    # === CLOUD / CONTAINER SECURITY ===
    {"name": "Trivy", "slug": "trivy", "category": "Cloud / Container Security", "description": "Comprehensive security scanner for containers and filesystems", "executable_name": "trivy", "install_method": "apt", "install_command_linux": "sudo apt install -y trivy", "risk_level": "low", "supports_linux": True, "supports_windows": True, "is_featured": True, "github_url": "https://github.com/aquasecurity/trivy", "tags": ["container", "vulnerability", "iac"]},
    {"name": "Grype", "slug": "grype", "category": "Cloud / Container Security", "description": "Vulnerability scanner for container images", "executable_name": "grype", "install_method": "github", "github_repo": "anchore/grype", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["container", "vulnerability"]},
    {"name": "ScoutSuite", "slug": "scoutsuite", "category": "Cloud / Container Security", "description": "Multi-cloud security auditing tool", "executable_name": "scout", "install_method": "pip", "install_command_linux": "pip3 install scoutsuite", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["cloud", "aws", "azure", "gcp"]},
    {"name": "Prowler", "slug": "prowler", "category": "Cloud / Container Security", "description": "AWS and Azure security best practices assessment", "executable_name": "prowler", "install_method": "pip", "install_command_linux": "pip3 install prowler", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["aws", "compliance", "audit"]},

    # === ACTIVE DIRECTORY / INTERNAL ===
    {"name": "BloodHound", "slug": "bloodhound", "category": "Active Directory / Internal", "description": "Active Directory relationship explorer", "executable_name": "bloodhound", "install_method": "apt", "install_command_linux": "sudo apt install -y bloodhound", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "tags": ["ad", "graph", "relationships"]},
    {"name": "NetExec", "slug": "netexec", "category": "Active Directory / Internal", "description": "Network service exploitation tool (CrackMapExec successor)", "executable_name": "nxc", "install_method": "pip", "install_command_linux": "pip3 install netexec", "risk_level": "high", "supports_linux": True, "tags": ["smb", "ad", "lateral"]},
    {"name": "Impacket", "slug": "impacket", "category": "Active Directory / Internal", "description": "Collection of Python classes for working with network protocols", "executable_name": "impacket-smbclient", "install_method": "pip", "install_command_linux": "pip3 install impacket", "risk_level": "high", "supports_linux": True, "tags": ["smb", "kerberos", "protocols"]},
    {"name": "Responder", "slug": "responder", "category": "Active Directory / Internal", "description": "LLMNR/NBT-NS/MDNS poisoner and relay tool", "executable_name": "responder", "install_method": "apt", "install_command_linux": "sudo apt install -y responder", "risk_level": "high", "supports_linux": True, "tags": ["poisoning", "relay", "ntlm"]},

    # === REPORTING ===
    {"name": "DefectDojo", "slug": "defectdojo", "category": "Reporting", "description": "Open-source vulnerability management platform", "executable_name": "defectdojo", "install_method": "github", "github_repo": "DefectDojo/django-DefectDojo", "risk_level": "low", "supports_linux": True, "tags": ["reporting", "management"]},
]

# Categories with metadata
STORE_CATEGORIES = [
    {"name": "Recon / Scanning", "icon": "Radar", "color": "#06b6d4", "description": "Network discovery and asset mapping"},
    {"name": "Web Testing", "icon": "Globe", "color": "#8b5cf6", "description": "Web application security testing"},
    {"name": "Vulnerability / Exploit", "icon": "Bug", "color": "#ef4444", "description": "Vulnerability research and exploitation"},
    {"name": "Payload / Lab Utilities", "icon": "Bomb", "color": "#dc2626", "description": "Authorized payload generation for lab environments"},
    {"name": "Password / Hash Testing", "icon": "Key", "color": "#f59e0b", "description": "Password cracking and hash analysis"},
    {"name": "Wireless / WiFi Lab", "icon": "Wifi", "color": "#10b981", "description": "Wireless network security tools"},
    {"name": "Network Analysis", "icon": "Network", "color": "#3b82f6", "description": "Network traffic analysis and monitoring"},
    {"name": "OSINT", "icon": "Search", "color": "#6366f1", "description": "Open source intelligence gathering"},
    {"name": "Forensics / Malware Analysis", "icon": "Microscope", "color": "#ec4899", "description": "Digital forensics and malware reverse engineering"},
    {"name": "Cloud / Container Security", "icon": "Cloud", "color": "#14b8a6", "description": "Cloud infrastructure and container security"},
    {"name": "Active Directory / Internal", "icon": "Server", "color": "#f97316", "description": "Active Directory and internal network testing"},
    {"name": "Reporting", "icon": "FileText", "color": "#64748b", "description": "Vulnerability management and reporting"},
]
