"""
VIGIL LABS - Complete Tool Store Catalog
200+ cybersecurity, pentesting, OSCP, CTF, bug bounty, forensics, and DevOps tools.
Every tool that matters — nothing left out.
"""

TOOL_CATALOG = [
    # ═══════════════════════════════════════════════════════════════════════
    # RECON / SCANNING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Nmap", "slug": "nmap", "category": "Recon / Scanning", "description": "Network discovery and security auditing tool", "executable_name": "nmap", "install_method": "apt", "install_command_linux": "sudo apt install -y nmap", "install_command_windows": "choco install nmap -y", "install_command_macos": "brew install nmap", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "github_url": "https://github.com/nmap/nmap", "tags": ["network", "scanner", "ports"]},
    {"name": "Masscan", "slug": "masscan", "category": "Recon / Scanning", "description": "Fastest Internet port scanner", "executable_name": "masscan", "install_method": "apt", "install_command_linux": "sudo apt install -y masscan", "install_command_macos": "brew install masscan", "risk_level": "high", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["network", "fast-scanner"]},
    {"name": "Rustscan", "slug": "rustscan", "category": "Recon / Scanning", "description": "Fast port scanner written in Rust", "executable_name": "rustscan", "install_method": "github", "github_repo": "RustScan/RustScan", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["rust", "fast-scanner"]},
    {"name": "Naabu", "slug": "naabu", "category": "Recon / Scanning", "description": "Fast port scanner focused on reliability", "executable_name": "naabu", "install_method": "github", "github_repo": "projectdiscovery/naabu", "risk_level": "medium", "supports_linux": True, "supports_macos": True, "tags": ["port", "scanner", "fast"]},
    {"name": "Amass", "slug": "amass", "category": "Recon / Scanning", "description": "In-depth attack surface mapping and asset discovery", "executable_name": "amass", "install_method": "apt", "install_command_linux": "sudo apt install -y amass", "install_command_macos": "brew install amass", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["recon", "subdomain", "osint"]},
    {"name": "Subfinder", "slug": "subfinder", "category": "Recon / Scanning", "description": "Fast passive subdomain enumeration tool", "executable_name": "subfinder", "install_method": "github", "github_repo": "projectdiscovery/subfinder", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["subdomain", "passive"]},

    {"name": "Assetfinder", "slug": "assetfinder", "category": "Recon / Scanning", "description": "Find domains and subdomains related to a given domain", "executable_name": "assetfinder", "install_method": "github", "github_repo": "tomnomnom/assetfinder", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["subdomain", "recon"]},
    {"name": "Httpx", "slug": "httpx", "category": "Recon / Scanning", "description": "Fast HTTP probing tool", "executable_name": "httpx", "install_method": "github", "github_repo": "projectdiscovery/httpx", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["http", "probe", "web"]},
    {"name": "Katana", "slug": "katana", "category": "Recon / Scanning", "description": "Next-generation crawling and spidering framework", "executable_name": "katana", "install_method": "github", "github_repo": "projectdiscovery/katana", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["crawler", "spider", "web"]},
    {"name": "WhatWeb", "slug": "whatweb", "category": "Recon / Scanning", "description": "Web scanner that identifies websites and technologies", "executable_name": "whatweb", "install_method": "apt", "install_command_linux": "sudo apt install -y whatweb", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["web", "fingerprint"]},
    {"name": "DNSx", "slug": "dnsx", "category": "Recon / Scanning", "description": "Fast multi-purpose DNS toolkit", "executable_name": "dnsx", "install_method": "github", "github_repo": "projectdiscovery/dnsx", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["dns", "resolution"]},
    {"name": "DNSRecon", "slug": "dnsrecon", "category": "Recon / Scanning", "description": "DNS enumeration and reconnaissance tool", "executable_name": "dnsrecon", "install_method": "pip", "install_command_linux": "pip3 install dnsrecon", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["dns", "enum"]},
    {"name": "gau", "slug": "gau", "category": "Recon / Scanning", "description": "Fetch known URLs from AlienVault, Wayback, Common Crawl", "executable_name": "gau", "install_method": "github", "github_repo": "lc/gau", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["urls", "osint"]},
    {"name": "waybackurls", "slug": "waybackurls", "category": "Recon / Scanning", "description": "Fetch URLs from the Wayback Machine", "executable_name": "waybackurls", "install_method": "github", "github_repo": "tomnomnom/waybackurls", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["urls", "wayback"]},
    {"name": "Fierce", "slug": "fierce", "category": "Recon / Scanning", "description": "DNS reconnaissance tool for locating non-contiguous IP space", "executable_name": "fierce", "install_method": "pip", "install_command_linux": "pip3 install fierce", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["dns", "recon"]},
    {"name": "Knockpy", "slug": "knockpy", "category": "Recon / Scanning", "description": "Subdomain scan and enumeration", "executable_name": "knockpy", "install_method": "pip", "install_command_linux": "pip3 install knock", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["subdomain", "enum"]},
    {"name": "Shodan CLI", "slug": "shodan-cli", "category": "Recon / Scanning", "description": "Command-line interface to Shodan search engine", "executable_name": "shodan", "install_method": "pip", "install_command_linux": "pip3 install shodan", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["shodan", "iot", "search"]},
    {"name": "Censys CLI", "slug": "censys", "category": "Recon / Scanning", "description": "Censys search API client", "executable_name": "censys", "install_method": "pip", "install_command_linux": "pip3 install censys", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["censys", "search"]},

    # ═══════════════════════════════════════════════════════════════════════
    # WEB TESTING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Nikto", "slug": "nikto", "category": "Web Testing", "description": "Web server scanner for vulnerabilities", "executable_name": "nikto", "install_method": "apt", "install_command_linux": "sudo apt install -y nikto", "risk_level": "medium", "supports_linux": True, "supports_macos": True, "tags": ["web", "vulnerability", "scanner"]},
    {"name": "Nuclei", "slug": "nuclei", "category": "Web Testing", "description": "Fast vulnerability scanner based on templates", "executable_name": "nuclei", "install_method": "github", "github_repo": "projectdiscovery/nuclei", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["vulnerability", "templates", "fast"]},
    {"name": "SQLMap", "slug": "sqlmap", "category": "Web Testing", "description": "Automatic SQL injection and database takeover tool", "executable_name": "sqlmap", "install_method": "pip", "install_command_linux": "pip3 install sqlmap", "risk_level": "high", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["sql", "injection", "database"]},
    {"name": "ffuf", "slug": "ffuf", "category": "Web Testing", "description": "Fast web fuzzer written in Go", "executable_name": "ffuf", "install_method": "apt", "install_command_linux": "sudo apt install -y ffuf", "install_command_macos": "brew install ffuf", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["fuzzer", "web", "fast"]},
    {"name": "Gobuster", "slug": "gobuster", "category": "Web Testing", "description": "Directory/file & DNS busting tool written in Go", "executable_name": "gobuster", "install_method": "apt", "install_command_linux": "sudo apt install -y gobuster", "install_command_macos": "brew install gobuster", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["web", "directory", "dns"]},
    {"name": "Dirsearch", "slug": "dirsearch", "category": "Web Testing", "description": "Web path scanner/directory brute-forcer", "executable_name": "dirsearch", "install_method": "pip", "install_command_linux": "pip3 install dirsearch", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["web", "directory", "bruteforce"]},
    {"name": "Feroxbuster", "slug": "feroxbuster", "category": "Web Testing", "description": "Fast, recursive content discovery tool", "executable_name": "feroxbuster", "install_method": "apt", "install_command_linux": "sudo apt install -y feroxbuster", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["web", "recursive", "fast"]},
    {"name": "Dalfox", "slug": "dalfox", "category": "Web Testing", "description": "Parameter analysis and XSS scanning tool", "executable_name": "dalfox", "install_method": "github", "github_repo": "hahwul/dalfox", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["xss", "web", "scanner"]},
    {"name": "XSStrike", "slug": "xsstrike", "category": "Web Testing", "description": "Advanced XSS detection suite", "executable_name": "xsstrike", "install_method": "github", "github_repo": "s0md3v/XSStrike", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["xss", "web"]},
    {"name": "WPScan", "slug": "wpscan", "category": "Web Testing", "description": "WordPress vulnerability scanner", "executable_name": "wpscan", "install_method": "apt", "install_command_linux": "sudo apt install -y wpscan", "install_command_macos": "brew install wpscanteam/tap/wpscan", "risk_level": "medium", "supports_linux": True, "supports_macos": True, "tags": ["wordpress", "cms", "scanner"]},
    {"name": "Arjun", "slug": "arjun", "category": "Web Testing", "description": "HTTP parameter discovery suite", "executable_name": "arjun", "install_method": "pip", "install_command_linux": "pip3 install arjun", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["parameters", "web"]},
    {"name": "wfuzz", "slug": "wfuzz", "category": "Web Testing", "description": "Web application fuzzer", "executable_name": "wfuzz", "install_method": "pip", "install_command_linux": "pip3 install wfuzz", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["fuzzer", "web"]},
    {"name": "wafw00f", "slug": "wafw00f", "category": "Web Testing", "description": "Identify and fingerprint Web Application Firewalls", "executable_name": "wafw00f", "install_method": "pip", "install_command_linux": "pip3 install wafw00f", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["waf", "fingerprint"]},
    {"name": "Commix", "slug": "commix", "category": "Web Testing", "description": "Automated OS command injection exploitation", "executable_name": "commix", "install_method": "apt", "install_command_linux": "sudo apt install -y commix", "risk_level": "high", "supports_linux": True, "supports_macos": True, "tags": ["command-injection", "web"]},
    {"name": "NoSQLMap", "slug": "nosqlmap", "category": "Web Testing", "description": "Automated NoSQL database enumeration and exploitation", "executable_name": "nosqlmap", "install_method": "github", "github_repo": "codingo/NoSQLMap", "risk_level": "high", "supports_linux": True, "supports_macos": True, "tags": ["nosql", "mongodb", "injection"]},
    {"name": "ParamSpider", "slug": "paramspider", "category": "Web Testing", "description": "Mining URLs from dark corners of Web Archives for parameters", "executable_name": "paramspider", "install_method": "github", "github_repo": "devanshbatham/ParamSpider", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["parameters", "web", "recon"]},


    # ═══════════════════════════════════════════════════════════════════════
    # VULNERABILITY / EXPLOITATION
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Metasploit Framework", "slug": "metasploit", "category": "Exploitation", "description": "Advanced open-source exploitation framework", "executable_name": "msfconsole", "install_method": "apt", "install_command_linux": "sudo apt install -y metasploit-framework", "risk_level": "critical", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["exploit", "framework", "pentest"]},
    {"name": "SearchSploit", "slug": "searchsploit", "category": "Exploitation", "description": "Command-line search for Exploit-DB", "executable_name": "searchsploit", "install_method": "apt", "install_command_linux": "sudo apt install -y exploitdb", "risk_level": "low", "supports_linux": True, "tags": ["exploit", "search", "database"]},
    {"name": "msfvenom", "slug": "msfvenom", "category": "Exploitation", "description": "Payload generation (part of Metasploit)", "executable_name": "msfvenom", "install_method": "apt", "install_command_linux": "sudo apt install -y metasploit-framework", "risk_level": "critical", "supports_linux": True, "supports_macos": True, "tags": ["payload", "generation"]},
    {"name": "CVEMap", "slug": "cvemap", "category": "Exploitation", "description": "Navigate the CVE jungle with ease", "executable_name": "cvemap", "install_method": "github", "github_repo": "projectdiscovery/cvemap", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["cve", "vulnerability"]},

    # ═══════════════════════════════════════════════════════════════════════
    # POST-EXPLOITATION / PRIVILEGE ESCALATION
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "LinPEAS", "slug": "linpeas", "category": "Post-Exploitation", "description": "Linux Privilege Escalation Awesome Script", "executable_name": "linpeas.sh", "install_method": "github", "github_repo": "peass-ng/PEASS-ng", "risk_level": "medium", "supports_linux": True, "is_featured": True, "tags": ["privesc", "linux", "enum"]},
    {"name": "WinPEAS", "slug": "winpeas", "category": "Post-Exploitation", "description": "Windows Privilege Escalation Awesome Script", "executable_name": "winPEASany.exe", "install_method": "github", "github_repo": "peass-ng/PEASS-ng", "risk_level": "medium", "supports_windows": True, "is_featured": True, "tags": ["privesc", "windows", "enum"]},
    {"name": "linux-exploit-suggester", "slug": "linux-exploit-suggester", "category": "Post-Exploitation", "description": "Suggest exploits for Linux kernel version", "executable_name": "linux-exploit-suggester.sh", "install_method": "github", "github_repo": "The-Z-Labs/linux-exploit-suggester", "risk_level": "medium", "supports_linux": True, "tags": ["kernel", "privesc", "linux"]},
    {"name": "pspy", "slug": "pspy", "category": "Post-Exploitation", "description": "Monitor processes without root (unprivileged)", "executable_name": "pspy64", "install_method": "github", "github_repo": "DominicBreuker/pspy", "risk_level": "low", "supports_linux": True, "tags": ["process", "monitor", "privesc"]},
    {"name": "GTFOBins Lookup", "slug": "gtfobins", "category": "Post-Exploitation", "description": "Curated list of Unix binaries for privilege escalation", "executable_name": "gtfobins", "install_method": "manual", "github_url": "https://gtfobins.github.io", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["privesc", "reference"]},
    {"name": "Chisel", "slug": "chisel", "category": "Post-Exploitation", "description": "Fast TCP/UDP tunnel over HTTP (pivoting)", "executable_name": "chisel", "install_method": "github", "github_repo": "jpillora/chisel", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["tunnel", "pivot", "proxy"]},
    {"name": "Ligolo-ng", "slug": "ligolo-ng", "category": "Post-Exploitation", "description": "Advanced tunneling/pivoting tool using TUN interfaces", "executable_name": "ligolo-proxy", "install_method": "github", "github_repo": "nicocha30/ligolo-ng", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["tunnel", "pivot"]},
    {"name": "Socat", "slug": "socat", "category": "Post-Exploitation", "description": "Multipurpose relay (socket cat) for bidirectional data", "executable_name": "socat", "install_method": "apt", "install_command_linux": "sudo apt install -y socat", "install_command_macos": "brew install socat", "risk_level": "medium", "supports_linux": True, "supports_macos": True, "tags": ["relay", "shell", "pivot"]},
    {"name": "Evil-WinRM", "slug": "evil-winrm", "category": "Post-Exploitation", "description": "WinRM shell for pentesting Windows", "executable_name": "evil-winrm", "install_method": "apt", "install_command_linux": "sudo apt install -y evil-winrm", "risk_level": "high", "supports_linux": True, "tags": ["winrm", "windows", "shell"]},

    # ═══════════════════════════════════════════════════════════════════════
    # PASSWORD / HASH CRACKING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Hashcat", "slug": "hashcat", "category": "Password Cracking", "description": "World's fastest password recovery utility (GPU)", "executable_name": "hashcat", "install_method": "apt", "install_command_linux": "sudo apt install -y hashcat", "install_command_macos": "brew install hashcat", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["password", "hash", "gpu"]},
    {"name": "John the Ripper", "slug": "john", "category": "Password Cracking", "description": "Fast password cracker", "executable_name": "john", "install_method": "apt", "install_command_linux": "sudo apt install -y john", "install_command_macos": "brew install john", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["password", "cracker"]},
    {"name": "Hydra", "slug": "hydra", "category": "Password Cracking", "description": "Network login cracker supporting many protocols", "executable_name": "hydra", "install_method": "apt", "install_command_linux": "sudo apt install -y hydra", "install_command_macos": "brew install hydra", "risk_level": "high", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["bruteforce", "network", "login"]},
    {"name": "Medusa", "slug": "medusa", "category": "Password Cracking", "description": "Speedy parallel network login auditor", "executable_name": "medusa", "install_method": "apt", "install_command_linux": "sudo apt install -y medusa", "risk_level": "high", "supports_linux": True, "tags": ["bruteforce", "parallel"]},
    {"name": "CeWL", "slug": "cewl", "category": "Password Cracking", "description": "Custom wordlist generator by spidering websites", "executable_name": "cewl", "install_method": "apt", "install_command_linux": "sudo apt install -y cewl", "risk_level": "low", "supports_linux": True, "tags": ["wordlist", "generator"]},
    {"name": "Crunch", "slug": "crunch", "category": "Password Cracking", "description": "Wordlist generator with specified character sets", "executable_name": "crunch", "install_method": "apt", "install_command_linux": "sudo apt install -y crunch", "risk_level": "low", "supports_linux": True, "tags": ["wordlist", "generator"]},
    {"name": "hashid", "slug": "hashid", "category": "Password Cracking", "description": "Identify the type of a given hash", "executable_name": "hashid", "install_method": "pip", "install_command_linux": "pip3 install hashid", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["hash", "identify"]},
    {"name": "Name-That-Hash", "slug": "name-that-hash", "category": "Password Cracking", "description": "Modern hash identifier", "executable_name": "nth", "install_method": "pip", "install_command_linux": "pip3 install name-that-hash", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["hash", "identify"]},
    {"name": "Ophcrack", "slug": "ophcrack", "category": "Password Cracking", "description": "Windows password cracker using rainbow tables", "executable_name": "ophcrack", "install_method": "apt", "install_command_linux": "sudo apt install -y ophcrack", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "tags": ["windows", "rainbow"]},

    # ═══════════════════════════════════════════════════════════════════════
    # WIRELESS / WIFI
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Aircrack-ng", "slug": "aircrack-ng", "category": "Wireless", "description": "Complete suite of WiFi security tools", "executable_name": "aircrack-ng", "install_method": "apt", "install_command_linux": "sudo apt install -y aircrack-ng", "install_command_macos": "brew install aircrack-ng", "risk_level": "high", "supports_linux": True, "supports_macos": True, "is_featured": True, "tags": ["wifi", "cracking", "monitoring"]},
    {"name": "Wifite", "slug": "wifite", "category": "Wireless", "description": "Automated wireless attack tool", "executable_name": "wifite", "install_method": "apt", "install_command_linux": "sudo apt install -y wifite", "risk_level": "high", "supports_linux": True, "tags": ["wifi", "automated"]},
    {"name": "Bettercap", "slug": "bettercap", "category": "Wireless", "description": "Swiss Army knife for network attacks and monitoring", "executable_name": "bettercap", "install_method": "apt", "install_command_linux": "sudo apt install -y bettercap", "install_command_macos": "brew install bettercap", "risk_level": "high", "supports_linux": True, "supports_macos": True, "tags": ["mitm", "network", "wifi"]},
    {"name": "Kismet", "slug": "kismet", "category": "Wireless", "description": "Wireless network and device detector/sniffer", "executable_name": "kismet", "install_method": "apt", "install_command_linux": "sudo apt install -y kismet", "risk_level": "medium", "supports_linux": True, "tags": ["wifi", "sniffer"]},
    {"name": "Reaver", "slug": "reaver", "category": "Wireless", "description": "WPS brute force attack tool", "executable_name": "reaver", "install_method": "apt", "install_command_linux": "sudo apt install -y reaver", "risk_level": "high", "supports_linux": True, "tags": ["wps", "bruteforce"]},
    {"name": "Fern WiFi Cracker", "slug": "fern-wifi-cracker", "category": "Wireless", "description": "GUI-based WiFi auditing tool", "executable_name": "fern-wifi-cracker", "install_method": "apt", "install_command_linux": "sudo apt install -y fern-wifi-cracker", "risk_level": "high", "supports_linux": True, "tags": ["wifi", "gui"]},


    # ═══════════════════════════════════════════════════════════════════════
    # ACTIVE DIRECTORY / INTERNAL NETWORK
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "BloodHound", "slug": "bloodhound", "category": "Active Directory", "description": "AD relationship explorer and attack path mapper", "executable_name": "bloodhound", "install_method": "apt", "install_command_linux": "sudo apt install -y bloodhound", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "is_featured": True, "tags": ["ad", "graph", "relationships"]},
    {"name": "NetExec (nxc)", "slug": "netexec", "category": "Active Directory", "description": "Network service exploitation (CrackMapExec successor)", "executable_name": "nxc", "install_method": "pip", "install_command_linux": "pip3 install netexec", "risk_level": "high", "supports_linux": True, "supports_macos": True, "tags": ["smb", "ad", "lateral"]},
    {"name": "Impacket", "slug": "impacket", "category": "Active Directory", "description": "Python classes for working with network protocols (SMB, Kerberos, etc.)", "executable_name": "impacket-smbclient", "install_method": "pip", "install_command_linux": "pip3 install impacket", "risk_level": "high", "supports_linux": True, "supports_macos": True, "is_featured": True, "tags": ["smb", "kerberos", "protocols"]},
    {"name": "Responder", "slug": "responder", "category": "Active Directory", "description": "LLMNR/NBT-NS/MDNS poisoner and relay tool", "executable_name": "responder", "install_method": "apt", "install_command_linux": "sudo apt install -y responder", "risk_level": "high", "supports_linux": True, "tags": ["poisoning", "relay", "ntlm"]},
    {"name": "Kerbrute", "slug": "kerbrute", "category": "Active Directory", "description": "Kerberos brute-forcer and user enumeration", "executable_name": "kerbrute", "install_method": "github", "github_repo": "ropnop/kerbrute", "risk_level": "high", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["kerberos", "bruteforce", "enum"]},
    {"name": "enum4linux-ng", "slug": "enum4linux-ng", "category": "Active Directory", "description": "Next-generation SMB/RPC enumeration tool", "executable_name": "enum4linux-ng", "install_method": "pip", "install_command_linux": "pip3 install enum4linux-ng", "risk_level": "medium", "supports_linux": True, "tags": ["smb", "enum", "ad"]},
    {"name": "ldapdomaindump", "slug": "ldapdomaindump", "category": "Active Directory", "description": "Dump AD info via LDAP", "executable_name": "ldapdomaindump", "install_method": "pip", "install_command_linux": "pip3 install ldapdomaindump", "risk_level": "medium", "supports_linux": True, "tags": ["ldap", "ad", "dump"]},
    {"name": "Rubeus", "slug": "rubeus", "category": "Active Directory", "description": "Kerberos interaction and abuse toolkit (Windows)", "executable_name": "Rubeus.exe", "install_method": "github", "github_repo": "GhostPack/Rubeus", "risk_level": "high", "supports_windows": True, "tags": ["kerberos", "tickets", "windows"]},

    # ═══════════════════════════════════════════════════════════════════════
    # NETWORK ANALYSIS / SNIFFING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Wireshark", "slug": "wireshark", "category": "Network Analysis", "description": "World's most popular network protocol analyzer", "executable_name": "wireshark", "install_method": "apt", "install_command_linux": "sudo apt install -y wireshark", "install_command_windows": "choco install wireshark -y", "install_command_macos": "brew install --cask wireshark", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["packet", "capture", "analysis"]},
    {"name": "Tshark", "slug": "tshark", "category": "Network Analysis", "description": "Terminal-based protocol analyzer", "executable_name": "tshark", "install_method": "apt", "install_command_linux": "sudo apt install -y tshark", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["packet", "cli"]},
    {"name": "Tcpdump", "slug": "tcpdump", "category": "Network Analysis", "description": "Command-line packet analyzer", "executable_name": "tcpdump", "install_method": "apt", "install_command_linux": "sudo apt install -y tcpdump", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["packet", "capture", "cli"]},
    {"name": "Ettercap", "slug": "ettercap", "category": "Network Analysis", "description": "Comprehensive suite for MITM attacks on LAN", "executable_name": "ettercap", "install_method": "apt", "install_command_linux": "sudo apt install -y ettercap-common", "risk_level": "high", "supports_linux": True, "tags": ["mitm", "arp", "sniffing"]},
    {"name": "mitmproxy", "slug": "mitmproxy", "category": "Network Analysis", "description": "Interactive HTTPS proxy for traffic interception", "executable_name": "mitmproxy", "install_method": "pip", "install_command_linux": "pip3 install mitmproxy", "install_command_macos": "brew install mitmproxy", "risk_level": "medium", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["proxy", "mitm", "https"]},
    {"name": "Netdiscover", "slug": "netdiscover", "category": "Network Analysis", "description": "Active/passive ARP reconnaissance tool", "executable_name": "netdiscover", "install_method": "apt", "install_command_linux": "sudo apt install -y netdiscover", "risk_level": "low", "supports_linux": True, "tags": ["arp", "discovery"]},
    {"name": "sslscan", "slug": "sslscan", "category": "Network Analysis", "description": "Test SSL/TLS supported ciphers", "executable_name": "sslscan", "install_method": "apt", "install_command_linux": "sudo apt install -y sslscan", "install_command_macos": "brew install sslscan", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["ssl", "tls"]},
    {"name": "testssl.sh", "slug": "testssl", "category": "Network Analysis", "description": "Check TLS/SSL ciphers, protocols and crypto flaws", "executable_name": "testssl.sh", "install_method": "github", "github_repo": "drwetter/testssl.sh", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["ssl", "tls", "audit"]},

    # ═══════════════════════════════════════════════════════════════════════
    # OSINT
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "theHarvester", "slug": "theharvester", "category": "OSINT", "description": "Gather emails, subdomains, hosts from public sources", "executable_name": "theHarvester", "install_method": "apt", "install_command_linux": "sudo apt install -y theharvester", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["email", "subdomain", "recon"]},
    {"name": "Sherlock", "slug": "sherlock", "category": "OSINT", "description": "Hunt down social media accounts by username", "executable_name": "sherlock", "install_method": "pip", "install_command_linux": "pip3 install sherlock-project", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["social-media", "username"]},
    {"name": "Maigret", "slug": "maigret", "category": "OSINT", "description": "Collect a dossier on a person by username across 2500+ sites", "executable_name": "maigret", "install_method": "pip", "install_command_linux": "pip3 install maigret", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["username", "osint"]},
    {"name": "SpiderFoot", "slug": "spiderfoot", "category": "OSINT", "description": "Open source intelligence automation", "executable_name": "spiderfoot", "install_method": "pip", "install_command_linux": "pip3 install spiderfoot", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["automation", "osint"]},
    {"name": "Recon-ng", "slug": "recon-ng", "category": "OSINT", "description": "Web reconnaissance framework", "executable_name": "recon-ng", "install_method": "apt", "install_command_linux": "sudo apt install -y recon-ng", "risk_level": "low", "supports_linux": True, "tags": ["framework", "recon"]},
    {"name": "Holehe", "slug": "holehe", "category": "OSINT", "description": "Check if email is used on different sites", "executable_name": "holehe", "install_method": "pip", "install_command_linux": "pip3 install holehe", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["email", "lookup"]},
    {"name": "Photon", "slug": "photon", "category": "OSINT", "description": "Fast crawler designed for OSINT", "executable_name": "photon", "install_method": "github", "github_repo": "s0md3v/Photon", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["crawler", "osint"]},
    {"name": "Maltego", "slug": "maltego", "category": "OSINT", "description": "Visual link analysis for OSINT and forensics", "executable_name": "maltego", "install_method": "manual", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["graph", "visual", "osint"]},

    # ═══════════════════════════════════════════════════════════════════════
    # FORENSICS / REVERSE ENGINEERING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Volatility3", "slug": "volatility", "category": "Forensics", "description": "Advanced memory forensics framework", "executable_name": "vol", "install_method": "pip", "install_command_linux": "pip3 install volatility3", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["memory", "forensics"]},
    {"name": "Binwalk", "slug": "binwalk", "category": "Forensics", "description": "Firmware analysis and extraction tool", "executable_name": "binwalk", "install_method": "apt", "install_command_linux": "sudo apt install -y binwalk", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["firmware", "extraction"]},
    {"name": "ExifTool", "slug": "exiftool", "category": "Forensics", "description": "Read, write, and manipulate file metadata", "executable_name": "exiftool", "install_method": "apt", "install_command_linux": "sudo apt install -y libimage-exiftool-perl", "install_command_macos": "brew install exiftool", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["metadata", "images"]},
    {"name": "YARA", "slug": "yara", "category": "Forensics", "description": "Pattern matching tool for malware research", "executable_name": "yara", "install_method": "apt", "install_command_linux": "sudo apt install -y yara", "install_command_macos": "brew install yara", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["malware", "patterns"]},
    {"name": "Radare2", "slug": "radare2", "category": "Forensics", "description": "Advanced hexadecimal editor and disassembler", "executable_name": "r2", "install_method": "apt", "install_command_linux": "sudo apt install -y radare2", "install_command_macos": "brew install radare2", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["reverse", "disassembler"]},
    {"name": "Ghidra", "slug": "ghidra", "category": "Forensics", "description": "NSA's software reverse engineering framework", "executable_name": "ghidra", "install_method": "manual", "github_url": "https://github.com/NationalSecurityAgency/ghidra", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["reverse", "decompiler", "nsa"]},
    {"name": "Steghide", "slug": "steghide", "category": "Forensics", "description": "Hide/extract data in image/audio (steganography)", "executable_name": "steghide", "install_method": "apt", "install_command_linux": "sudo apt install -y steghide", "risk_level": "low", "supports_linux": True, "tags": ["steganography"]},
    {"name": "Foremost", "slug": "foremost", "category": "Forensics", "description": "Recover files based on headers and footers", "executable_name": "foremost", "install_method": "apt", "install_command_linux": "sudo apt install -y foremost", "risk_level": "low", "supports_linux": True, "tags": ["carving", "recovery"]},
    {"name": "Autopsy", "slug": "autopsy", "category": "Forensics", "description": "Digital forensics platform (GUI)", "executable_name": "autopsy", "install_method": "apt", "install_command_linux": "sudo apt install -y autopsy", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["forensics", "gui", "disk"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CLOUD / CONTAINER SECURITY
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Trivy", "slug": "trivy", "category": "Cloud Security", "description": "Comprehensive scanner for containers, IaC, and filesystems", "executable_name": "trivy", "install_method": "apt", "install_command_linux": "sudo apt install -y trivy", "install_command_macos": "brew install trivy", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["container", "vulnerability", "iac"]},
    {"name": "Gitleaks", "slug": "gitleaks", "category": "Cloud Security", "description": "Detect hardcoded secrets in git repos", "executable_name": "gitleaks", "install_method": "github", "github_repo": "gitleaks/gitleaks", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["secrets", "git"]},
    {"name": "Semgrep", "slug": "semgrep", "category": "Cloud Security", "description": "Static analysis for bugs and security issues", "executable_name": "semgrep", "install_method": "pip", "install_command_linux": "pip3 install semgrep", "install_command_macos": "brew install semgrep", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["sast", "code"]},
    {"name": "Prowler", "slug": "prowler", "category": "Cloud Security", "description": "AWS/Azure/GCP security best practices assessment", "executable_name": "prowler", "install_method": "pip", "install_command_linux": "pip3 install prowler", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["aws", "compliance"]},
    {"name": "ScoutSuite", "slug": "scoutsuite", "category": "Cloud Security", "description": "Multi-cloud security auditing tool", "executable_name": "scout", "install_method": "pip", "install_command_linux": "pip3 install scoutsuite", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["cloud", "aws", "azure"]},
    {"name": "Pacu", "slug": "pacu", "category": "Cloud Security", "description": "AWS exploitation framework", "executable_name": "pacu", "install_method": "pip", "install_command_linux": "pip3 install pacu", "risk_level": "high", "supports_linux": True, "supports_macos": True, "tags": ["aws", "exploit"]},
    {"name": "Checkov", "slug": "checkov", "category": "Cloud Security", "description": "Static analysis for IaC (Terraform, CloudFormation, K8s)", "executable_name": "checkov", "install_method": "pip", "install_command_linux": "pip3 install checkov", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["iac", "terraform"]},

    # ═══════════════════════════════════════════════════════════════════════
    # BLUE TEAM - IDS / IPS / MONITORING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Snort", "slug": "snort", "category": "Blue Team - IDS/IPS", "description": "Open-source network intrusion detection/prevention system", "executable_name": "snort", "install_method": "apt", "install_command_linux": "sudo apt install -y snort", "risk_level": "low", "supports_linux": True, "is_featured": True, "tags": ["ids", "ips", "network", "rules"]},
    {"name": "Suricata", "slug": "suricata", "category": "Blue Team - IDS/IPS", "description": "High-performance IDS/IPS and network security monitoring", "executable_name": "suricata", "install_method": "apt", "install_command_linux": "sudo apt install -y suricata", "install_command_macos": "brew install suricata", "risk_level": "low", "supports_linux": True, "supports_macos": True, "is_featured": True, "tags": ["ids", "ips", "network", "fast"]},
    {"name": "Zeek (Bro)", "slug": "zeek", "category": "Blue Team - IDS/IPS", "description": "Network analysis framework for security monitoring", "executable_name": "zeek", "install_method": "apt", "install_command_linux": "sudo apt install -y zeek", "install_command_macos": "brew install zeek", "risk_level": "low", "supports_linux": True, "supports_macos": True, "is_featured": True, "tags": ["network", "analysis", "monitoring", "logs"]},
    {"name": "OSSEC", "slug": "ossec", "category": "Blue Team - IDS/IPS", "description": "Host-based intrusion detection system (HIDS)", "executable_name": "ossec-control", "install_method": "manual", "github_url": "https://github.com/ossec/ossec-hids", "risk_level": "low", "supports_linux": True, "supports_windows": True, "tags": ["hids", "host", "integrity"]},
    {"name": "Wazuh", "slug": "wazuh", "category": "Blue Team - IDS/IPS", "description": "Unified XDR and SIEM protection (OSSEC fork)", "executable_name": "wazuh-agent", "install_method": "manual", "github_url": "https://github.com/wazuh/wazuh", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["xdr", "siem", "hids", "monitoring"]},
    {"name": "Fail2Ban", "slug": "fail2ban", "category": "Blue Team - IDS/IPS", "description": "Ban IPs with too many failed login attempts", "executable_name": "fail2ban-client", "install_method": "apt", "install_command_linux": "sudo apt install -y fail2ban", "risk_level": "low", "supports_linux": True, "tags": ["brute-force", "ban", "protection"]},

    # ═══════════════════════════════════════════════════════════════════════
    # BLUE TEAM - SIEM / LOG ANALYSIS
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Elastic SIEM (ELK)", "slug": "elastic-siem", "category": "Blue Team - SIEM", "description": "Elasticsearch + Logstash + Kibana for security analytics", "executable_name": "elasticsearch", "install_method": "manual", "github_url": "https://github.com/elastic/elasticsearch", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["siem", "logs", "analytics", "elk"]},
    {"name": "Splunk (Free)", "slug": "splunk", "category": "Blue Team - SIEM", "description": "Data platform for security monitoring and analytics", "executable_name": "splunk", "install_method": "manual", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["siem", "logs", "search", "analytics"]},
    {"name": "Graylog", "slug": "graylog", "category": "Blue Team - SIEM", "description": "Open-source log management and SIEM", "executable_name": "graylog-server", "install_method": "manual", "github_url": "https://github.com/Graylog2/graylog2-server", "risk_level": "low", "supports_linux": True, "tags": ["siem", "logs", "centralized"]},
    {"name": "Grafana", "slug": "grafana", "category": "Blue Team - SIEM", "description": "Observability dashboards for metrics, logs, traces", "executable_name": "grafana-server", "install_method": "apt", "install_command_linux": "sudo apt install -y grafana", "install_command_macos": "brew install grafana", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["dashboard", "monitoring", "visualization"]},
    {"name": "Sigma", "slug": "sigma", "category": "Blue Team - SIEM", "description": "Generic signature format for SIEM detection rules", "executable_name": "sigma", "install_method": "pip", "install_command_linux": "pip3 install pySigma", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["rules", "detection", "siem"]},

    # ═══════════════════════════════════════════════════════════════════════
    # BLUE TEAM - THREAT HUNTING / INCIDENT RESPONSE
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Velociraptor", "slug": "velociraptor", "category": "Blue Team - Threat Hunting", "description": "Endpoint visibility and digital forensics/IR tool", "executable_name": "velociraptor", "install_method": "github", "github_repo": "Velocidex/velociraptor", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "is_featured": True, "tags": ["edr", "forensics", "ir", "endpoint"]},
    {"name": "TheHive", "slug": "thehive", "category": "Blue Team - Threat Hunting", "description": "Security incident response platform", "executable_name": "thehive", "install_method": "manual", "github_url": "https://github.com/TheHive-Project/TheHive", "risk_level": "low", "supports_linux": True, "tags": ["incident-response", "cases", "collaboration"]},
    {"name": "MISP", "slug": "misp", "category": "Blue Team - Threat Hunting", "description": "Malware Information Sharing Platform for threat intelligence", "executable_name": "misp", "install_method": "manual", "github_url": "https://github.com/MISP/MISP", "risk_level": "low", "supports_linux": True, "tags": ["threat-intel", "ioc", "sharing"]},
    {"name": "OpenCTI", "slug": "opencti", "category": "Blue Team - Threat Hunting", "description": "Open Cyber Threat Intelligence platform", "executable_name": "opencti", "install_method": "manual", "github_url": "https://github.com/OpenCTI-Platform/opencti", "risk_level": "low", "supports_linux": True, "tags": ["threat-intel", "cti", "stix"]},
    {"name": "ClamAV", "slug": "clamav", "category": "Blue Team - Threat Hunting", "description": "Open-source antivirus engine for malware detection", "executable_name": "clamscan", "install_method": "apt", "install_command_linux": "sudo apt install -y clamav", "install_command_macos": "brew install clamav", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["antivirus", "malware", "scanning"]},
    {"name": "Chainsaw", "slug": "chainsaw", "category": "Blue Team - Threat Hunting", "description": "Rapidly search and hunt through Windows event logs", "executable_name": "chainsaw", "install_method": "github", "github_repo": "WithSecureLabs/chainsaw", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["evtx", "windows", "hunt", "sigma"]},
    {"name": "Hayabusa", "slug": "hayabusa", "category": "Blue Team - Threat Hunting", "description": "Windows event log fast forensics timeline generator", "executable_name": "hayabusa", "install_method": "github", "github_repo": "Yamato-Security/hayabusa", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["evtx", "timeline", "sigma", "forensics"]},
    {"name": "DeepBlueCLI", "slug": "deepbluecli", "category": "Blue Team - Threat Hunting", "description": "PowerShell module for Windows event log threat hunting", "executable_name": "DeepBlue.ps1", "install_method": "github", "github_repo": "sans-blue-team/DeepBlueCLI", "risk_level": "low", "supports_windows": True, "tags": ["powershell", "evtx", "hunting"]},

    # ═══════════════════════════════════════════════════════════════════════
    # BLUE TEAM - HARDENING / COMPLIANCE
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Lynis", "slug": "lynis", "category": "Blue Team - Hardening", "description": "Security auditing and hardening tool for Linux/macOS", "executable_name": "lynis", "install_method": "apt", "install_command_linux": "sudo apt install -y lynis", "install_command_macos": "brew install lynis", "risk_level": "low", "supports_linux": True, "supports_macos": True, "is_featured": True, "tags": ["audit", "hardening", "compliance"]},
    {"name": "OpenSCAP", "slug": "openscap", "category": "Blue Team - Hardening", "description": "SCAP security compliance checking framework", "executable_name": "oscap", "install_method": "apt", "install_command_linux": "sudo apt install -y libopenscap8", "risk_level": "low", "supports_linux": True, "tags": ["compliance", "scap", "cis"]},
    {"name": "RKHunter", "slug": "rkhunter", "category": "Blue Team - Hardening", "description": "Rootkit detection and system integrity checker", "executable_name": "rkhunter", "install_method": "apt", "install_command_linux": "sudo apt install -y rkhunter", "risk_level": "low", "supports_linux": True, "tags": ["rootkit", "integrity", "detection"]},
    {"name": "chkrootkit", "slug": "chkrootkit", "category": "Blue Team - Hardening", "description": "Check for signs of rootkits on Linux", "executable_name": "chkrootkit", "install_method": "apt", "install_command_linux": "sudo apt install -y chkrootkit", "risk_level": "low", "supports_linux": True, "tags": ["rootkit", "check"]},
    {"name": "AIDE", "slug": "aide", "category": "Blue Team - Hardening", "description": "Advanced Intrusion Detection Environment (file integrity)", "executable_name": "aide", "install_method": "apt", "install_command_linux": "sudo apt install -y aide", "risk_level": "low", "supports_linux": True, "tags": ["integrity", "fim", "detection"]},
    {"name": "UFW", "slug": "ufw", "category": "Blue Team - Hardening", "description": "Uncomplicated Firewall - easy iptables frontend", "executable_name": "ufw", "install_method": "apt", "install_command_linux": "sudo apt install -y ufw", "risk_level": "low", "supports_linux": True, "tags": ["firewall", "iptables", "simple"]},
    {"name": "Fail2Ban (Hardening)", "slug": "fail2ban-hardening", "category": "Blue Team - Hardening", "description": "Intrusion prevention via log monitoring and IP banning", "executable_name": "fail2ban-client", "install_method": "apt", "install_command_linux": "sudo apt install -y fail2ban", "risk_level": "low", "supports_linux": True, "tags": ["brute-force", "ban", "logs"]},

    # ═══════════════════════════════════════════════════════════════════════
    # BLUE TEAM - HONEYPOTS / DECEPTION
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Cowrie", "slug": "cowrie", "category": "Blue Team - Honeypots", "description": "Medium/high interaction SSH/Telnet honeypot", "executable_name": "cowrie", "install_method": "github", "github_repo": "cowrie/cowrie", "risk_level": "low", "supports_linux": True, "tags": ["honeypot", "ssh", "deception"]},
    {"name": "T-Pot", "slug": "tpot", "category": "Blue Team - Honeypots", "description": "All-in-one multi-honeypot platform (20+ honeypots)", "executable_name": "tpot", "install_method": "github", "github_repo": "telekom-security/tpotce", "risk_level": "low", "supports_linux": True, "is_featured": True, "tags": ["honeypot", "multi", "deception"]},
    {"name": "OpenCanary", "slug": "opencanary", "category": "Blue Team - Honeypots", "description": "Lightweight honeypot daemon for internal detection", "executable_name": "opencanaryd", "install_method": "pip", "install_command_linux": "pip3 install opencanary", "risk_level": "low", "supports_linux": True, "tags": ["honeypot", "canary", "detection"]},
    {"name": "HoneyD", "slug": "honeyd", "category": "Blue Team - Honeypots", "description": "Virtual honeypot framework to simulate network services", "executable_name": "honeyd", "install_method": "apt", "install_command_linux": "sudo apt install -y honeyd", "risk_level": "low", "supports_linux": True, "tags": ["honeypot", "virtual", "network"]},

    # ═══════════════════════════════════════════════════════════════════════
    # BLUE TEAM - MALWARE ANALYSIS / SANDBOXING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Cuckoo Sandbox", "slug": "cuckoo", "category": "Blue Team - Malware Analysis", "description": "Automated malware analysis sandbox", "executable_name": "cuckoo", "install_method": "pip", "install_command_linux": "pip3 install cuckoo", "risk_level": "low", "supports_linux": True, "tags": ["sandbox", "malware", "automated"]},
    {"name": "oletools", "slug": "oletools", "category": "Blue Team - Malware Analysis", "description": "Analyze MS Office files for malware (macros, OLE)", "executable_name": "olevba", "install_method": "pip", "install_command_linux": "pip3 install oletools", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["office", "macros", "malware"]},
    {"name": "FLOSS", "slug": "floss", "category": "Blue Team - Malware Analysis", "description": "Obfuscated String Solver for malware deobfuscation", "executable_name": "floss", "install_method": "pip", "install_command_linux": "pip3 install flare-floss", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["strings", "deobfuscation", "malware"]},
    {"name": "Detect-It-Easy", "slug": "detect-it-easy", "category": "Blue Team - Malware Analysis", "description": "Determine file type and packer identification", "executable_name": "die", "install_method": "github", "github_repo": "horsicq/Detect-It-Easy", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["packer", "identification", "binary"]},
    {"name": "pe-tree", "slug": "pe-tree", "category": "Blue Team - Malware Analysis", "description": "PE file analysis tool with tree view", "executable_name": "pe-tree", "install_method": "pip", "install_command_linux": "pip3 install pe-tree", "risk_level": "low", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["pe", "windows", "analysis"]},

    # ═══════════════════════════════════════════════════════════════════════
    # SOCIAL ENGINEERING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "GoPhish", "slug": "gophish", "category": "Social Engineering", "description": "Phishing simulation framework", "executable_name": "gophish", "install_method": "github", "github_repo": "gophish/gophish", "risk_level": "high", "supports_linux": True, "supports_windows": True, "supports_macos": True, "tags": ["phishing", "simulation"]},
    {"name": "SET (Social Engineering Toolkit)", "slug": "setoolkit", "category": "Social Engineering", "description": "Social engineering attack framework", "executable_name": "setoolkit", "install_method": "apt", "install_command_linux": "sudo apt install -y set", "risk_level": "critical", "supports_linux": True, "tags": ["phishing", "framework"]},

    # ═══════════════════════════════════════════════════════════════════════
    # REPORTING
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "SysReptor", "slug": "sysreptor", "category": "Reporting", "description": "Pentest reporting platform with templates", "executable_name": "sysreptor", "install_method": "github", "github_repo": "Syslifters/sysreptor", "risk_level": "low", "supports_linux": True, "supports_macos": True, "tags": ["reporting", "pentest"]},
    {"name": "DefectDojo", "slug": "defectdojo", "category": "Reporting", "description": "Vulnerability management and correlation", "executable_name": "defectdojo", "install_method": "github", "github_repo": "DefectDojo/django-DefectDojo", "risk_level": "low", "supports_linux": True, "tags": ["reporting", "management"]},
]


# Categories with metadata
STORE_CATEGORIES = [
    {"name": "Recon / Scanning", "icon": "Radar", "color": "#06b6d4", "description": "Network discovery, port scanning, subdomain enumeration, asset mapping"},
    {"name": "Web Testing", "icon": "Globe", "color": "#8b5cf6", "description": "Web app security testing, fuzzing, SQL injection, XSS"},
    {"name": "Exploitation", "icon": "Bug", "color": "#ef4444", "description": "Vulnerability exploitation, payload generation, CVE research"},
    {"name": "Post-Exploitation", "icon": "Shield", "color": "#dc2626", "description": "Privilege escalation, pivoting, tunneling, persistence"},
    {"name": "Password Cracking", "icon": "Key", "color": "#f59e0b", "description": "Hash cracking, brute-force, wordlist generation"},
    {"name": "Wireless", "icon": "Wifi", "color": "#10b981", "description": "WiFi security testing, WPA cracking, wireless monitoring"},
    {"name": "Active Directory", "icon": "Server", "color": "#f97316", "description": "AD enumeration, Kerberos attacks, lateral movement"},
    {"name": "Network Analysis", "icon": "Network", "color": "#3b82f6", "description": "Packet capture, traffic analysis, MITM, SSL testing"},
    {"name": "OSINT", "icon": "Search", "color": "#6366f1", "description": "Open source intelligence, username/email lookup, social media"},
    {"name": "Forensics", "icon": "Microscope", "color": "#ec4899", "description": "Memory forensics, disk analysis, malware RE, steganography"},
    {"name": "Cloud Security", "icon": "Cloud", "color": "#14b8a6", "description": "Cloud misconfiguration, container scanning, IaC security"},
    {"name": "Blue Team - IDS/IPS", "icon": "ShieldCheck", "color": "#0ea5e9", "description": "Intrusion detection/prevention, network monitoring, host-based security"},
    {"name": "Blue Team - SIEM", "icon": "BarChart3", "color": "#2563eb", "description": "Log management, security analytics, detection engineering"},
    {"name": "Blue Team - Threat Hunting", "icon": "Crosshair", "color": "#7c3aed", "description": "Threat intelligence, incident response, IOC scanning, EDR"},
    {"name": "Blue Team - Hardening", "icon": "Lock", "color": "#059669", "description": "System hardening, compliance auditing, firewall, integrity checking"},
    {"name": "Blue Team - Honeypots", "icon": "Zap", "color": "#eab308", "description": "Deception technology, honeypots, canary tokens"},
    {"name": "Blue Team - Malware Analysis", "icon": "FileSearch", "color": "#e11d48", "description": "Sandboxing, PE analysis, deobfuscation, Office macro analysis"},
    {"name": "Social Engineering", "icon": "Users", "color": "#a855f7", "description": "Phishing simulation, social engineering frameworks"},
    {"name": "Reporting", "icon": "FileText", "color": "#64748b", "description": "Pentest reporting and vulnerability management"},
]
